/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.bochk.hackathon.api.oauth.model.AddressCoordinates;
import com.bochk.hackathon.api.oauth.model.OpeningHours;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Branch
 */
public class Branch {
  @SerializedName("district_code")
  private String districtCode = null;

  @SerializedName("district_name")
  private String districtName = null;

  @SerializedName("branch_code")
  private String branchCode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("address_coordinates")
  private AddressCoordinates addressCoordinates = null;

  @SerializedName("phone_no")
  private String phoneNo = null;

  @SerializedName("opening_hours")
  private OpeningHours openingHours = null;

  @SerializedName("services")
  private List<String> services = new ArrayList<>();

  /**
   * Gets or Sets businessStatus
   */
  @JsonAdapter(BusinessStatusEnum.Adapter.class)
  public enum BusinessStatusEnum {
    UNCONGESTED("UNCONGESTED"),
    
    CONGESTED("CONGESTED"),
    
    VERY_CONGESTED("VERY_CONGESTED");

    private String value;

    BusinessStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BusinessStatusEnum fromValue(String text) {
      for (BusinessStatusEnum b : BusinessStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<BusinessStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BusinessStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BusinessStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return BusinessStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("business_status")
  private BusinessStatusEnum businessStatus = null;

  public Branch districtCode(String districtCode) {
    this.districtCode = districtCode;
    return this;
  }

   /**
   * Get districtCode
   * @return districtCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDistrictCode() {
    return districtCode;
  }

  public void setDistrictCode(String districtCode) {
    this.districtCode = districtCode;
  }

  public Branch districtName(String districtName) {
    this.districtName = districtName;
    return this;
  }

   /**
   * Get districtName
   * @return districtName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDistrictName() {
    return districtName;
  }

  public void setDistrictName(String districtName) {
    this.districtName = districtName;
  }

  public Branch branchCode(String branchCode) {
    this.branchCode = branchCode;
    return this;
  }

   /**
   * Get branchCode
   * @return branchCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBranchCode() {
    return branchCode;
  }

  public void setBranchCode(String branchCode) {
    this.branchCode = branchCode;
  }

  public Branch name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Branch address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Branch addressCoordinates(AddressCoordinates addressCoordinates) {
    this.addressCoordinates = addressCoordinates;
    return this;
  }

   /**
   * Get addressCoordinates
   * @return addressCoordinates
  **/
  @ApiModelProperty(required = true, value = "")
  public AddressCoordinates getAddressCoordinates() {
    return addressCoordinates;
  }

  public void setAddressCoordinates(AddressCoordinates addressCoordinates) {
    this.addressCoordinates = addressCoordinates;
  }

  public Branch phoneNo(String phoneNo) {
    this.phoneNo = phoneNo;
    return this;
  }

   /**
   * Get phoneNo
   * @return phoneNo
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPhoneNo() {
    return phoneNo;
  }

  public void setPhoneNo(String phoneNo) {
    this.phoneNo = phoneNo;
  }

  public Branch openingHours(OpeningHours openingHours) {
    this.openingHours = openingHours;
    return this;
  }

   /**
   * Get openingHours
   * @return openingHours
  **/
  @ApiModelProperty(required = true, value = "")
  public OpeningHours getOpeningHours() {
    return openingHours;
  }

  public void setOpeningHours(OpeningHours openingHours) {
    this.openingHours = openingHours;
  }

  public Branch services(List<String> services) {
    this.services = services;
    return this;
  }

  public Branch addServicesItem(String servicesItem) {
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @ApiModelProperty(example = "\"ATM_CENTRE\"", required = true, value = "")
  public List<String> getServices() {
    return services;
  }

  public void setServices(List<String> services) {
    this.services = services;
  }

  public Branch businessStatus(BusinessStatusEnum businessStatus) {
    this.businessStatus = businessStatus;
    return this;
  }

   /**
   * Get businessStatus
   * @return businessStatus
  **/
  @ApiModelProperty(value = "")
  public BusinessStatusEnum getBusinessStatus() {
    return businessStatus;
  }

  public void setBusinessStatus(BusinessStatusEnum businessStatus) {
    this.businessStatus = businessStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Branch branch = (Branch) o;
    return Objects.equals(this.districtCode, branch.districtCode) &&
        Objects.equals(this.districtName, branch.districtName) &&
        Objects.equals(this.branchCode, branch.branchCode) &&
        Objects.equals(this.name, branch.name) &&
        Objects.equals(this.address, branch.address) &&
        Objects.equals(this.addressCoordinates, branch.addressCoordinates) &&
        Objects.equals(this.phoneNo, branch.phoneNo) &&
        Objects.equals(this.openingHours, branch.openingHours) &&
        Objects.equals(this.services, branch.services) &&
        Objects.equals(this.businessStatus, branch.businessStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(districtCode, districtName, branchCode, name, address, addressCoordinates, phoneNo, openingHours, services, businessStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Branch {\n");
    
    sb.append("    districtCode: ").append(toIndentedString(districtCode)).append("\n");
    sb.append("    districtName: ").append(toIndentedString(districtName)).append("\n");
    sb.append("    branchCode: ").append(toIndentedString(branchCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressCoordinates: ").append(toIndentedString(addressCoordinates)).append("\n");
    sb.append("    phoneNo: ").append(toIndentedString(phoneNo)).append("\n");
    sb.append("    openingHours: ").append(toIndentedString(openingHours)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    businessStatus: ").append(toIndentedString(businessStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

