/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreditCardPaymentResponse
 */
public class CreditCardPaymentResponse {
  @SerializedName("credit_unused")
  private Double creditUnused = null;

  public CreditCardPaymentResponse creditUnused(Double creditUnused) {
    this.creditUnused = creditUnused;
    return this;
  }

   /**
   * Get creditUnused
   * @return creditUnused
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getCreditUnused() {
    return creditUnused;
  }

  public void setCreditUnused(Double creditUnused) {
    this.creditUnused = creditUnused;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditCardPaymentResponse creditCardPaymentResponse = (CreditCardPaymentResponse) o;
    return Objects.equals(this.creditUnused, creditCardPaymentResponse.creditUnused);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditUnused);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditCardPaymentResponse {\n");
    
    sb.append("    creditUnused: ").append(toIndentedString(creditUnused)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

