/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets currency
 */
@JsonAdapter(Currency.Adapter.class)
public enum Currency {
  
  HKD("HKD"),
  
  USD("USD"),
  
  CNY("CNY"),
  
  AUD("AUD"),
  
  CAD("CAD"),
  
  CHF("CHF"),
  
  EUR("EUR"),
  
  GBP("GBP"),
  
  JPY("JPY"),
  
  NZD("NZD"),
  
  SGD("SGD"),
  
  THB("THB"),
  
  BND("BND"),
  
  ZAR("ZAR"),
  
  DKK("DKK");

  private String value;

  Currency(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Currency fromValue(String text) {
    for (Currency b : Currency.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Currency> {
    @Override
    public void write(final JsonWriter jsonWriter, final Currency enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Currency read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Currency.fromValue(String.valueOf(value));
    }
  }
}

