/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.bochk.hackathon.api.oauth.model.Currency;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ForexRequest
 */
public class ForexRequest {
  @SerializedName("src_currency")
  private Currency srcCurrency = null;

  @SerializedName("dst_account_no")
  private String dstAccountNo = null;

  @SerializedName("dst_currency")
  private Currency dstCurrency = null;

  @SerializedName("dst_amount")
  private Double dstAmount = null;

  @SerializedName("rate")
  private Double rate = null;

  @SerializedName("remark")
  private String remark = null;

  public ForexRequest srcCurrency(Currency srcCurrency) {
    this.srcCurrency = srcCurrency;
    return this;
  }

   /**
   * Get srcCurrency
   * @return srcCurrency
  **/
  @ApiModelProperty(required = true, value = "")
  public Currency getSrcCurrency() {
    return srcCurrency;
  }

  public void setSrcCurrency(Currency srcCurrency) {
    this.srcCurrency = srcCurrency;
  }

  public ForexRequest dstAccountNo(String dstAccountNo) {
    this.dstAccountNo = dstAccountNo;
    return this;
  }

   /**
   * Destination account number
   * @return dstAccountNo
  **/
  @ApiModelProperty(required = true, value = "Destination account number")
  public String getDstAccountNo() {
    return dstAccountNo;
  }

  public void setDstAccountNo(String dstAccountNo) {
    this.dstAccountNo = dstAccountNo;
  }

  public ForexRequest dstCurrency(Currency dstCurrency) {
    this.dstCurrency = dstCurrency;
    return this;
  }

   /**
   * Get dstCurrency
   * @return dstCurrency
  **/
  @ApiModelProperty(required = true, value = "")
  public Currency getDstCurrency() {
    return dstCurrency;
  }

  public void setDstCurrency(Currency dstCurrency) {
    this.dstCurrency = dstCurrency;
  }

  public ForexRequest dstAmount(Double dstAmount) {
    this.dstAmount = dstAmount;
    return this;
  }

   /**
   * Destination amount (in dollar)
   * @return dstAmount
  **/
  @ApiModelProperty(required = true, value = "Destination amount (in dollar)")
  public Double getDstAmount() {
    return dstAmount;
  }

  public void setDstAmount(Double dstAmount) {
    this.dstAmount = dstAmount;
  }

  public ForexRequest rate(Double rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Exchange rate
   * @return rate
  **/
  @ApiModelProperty(required = true, value = "Exchange rate")
  public Double getRate() {
    return rate;
  }

  public void setRate(Double rate) {
    this.rate = rate;
  }

  public ForexRequest remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * Free text remark
   * @return remark
  **/
  @ApiModelProperty(value = "Free text remark")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForexRequest forexRequest = (ForexRequest) o;
    return Objects.equals(this.srcCurrency, forexRequest.srcCurrency) &&
        Objects.equals(this.dstAccountNo, forexRequest.dstAccountNo) &&
        Objects.equals(this.dstCurrency, forexRequest.dstCurrency) &&
        Objects.equals(this.dstAmount, forexRequest.dstAmount) &&
        Objects.equals(this.rate, forexRequest.rate) &&
        Objects.equals(this.remark, forexRequest.remark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(srcCurrency, dstAccountNo, dstCurrency, dstAmount, rate, remark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForexRequest {\n");
    
    sb.append("    srcCurrency: ").append(toIndentedString(srcCurrency)).append("\n");
    sb.append("    dstAccountNo: ").append(toIndentedString(dstAccountNo)).append("\n");
    sb.append("    dstCurrency: ").append(toIndentedString(dstCurrency)).append("\n");
    sb.append("    dstAmount: ").append(toIndentedString(dstAmount)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

