/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MoneyTransferFpsResponse
 */
public class MoneyTransferFpsResponse {
  @SerializedName("src_balance_after")
  private Double srcBalanceAfter = null;

  @SerializedName("dst_account_name")
  private String dstAccountName = null;

  public MoneyTransferFpsResponse srcBalanceAfter(Double srcBalanceAfter) {
    this.srcBalanceAfter = srcBalanceAfter;
    return this;
  }

   /**
   * Get srcBalanceAfter
   * @return srcBalanceAfter
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getSrcBalanceAfter() {
    return srcBalanceAfter;
  }

  public void setSrcBalanceAfter(Double srcBalanceAfter) {
    this.srcBalanceAfter = srcBalanceAfter;
  }

  public MoneyTransferFpsResponse dstAccountName(String dstAccountName) {
    this.dstAccountName = dstAccountName;
    return this;
  }

   /**
   * Get dstAccountName
   * @return dstAccountName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDstAccountName() {
    return dstAccountName;
  }

  public void setDstAccountName(String dstAccountName) {
    this.dstAccountName = dstAccountName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoneyTransferFpsResponse moneyTransferFpsResponse = (MoneyTransferFpsResponse) o;
    return Objects.equals(this.srcBalanceAfter, moneyTransferFpsResponse.srcBalanceAfter) &&
        Objects.equals(this.dstAccountName, moneyTransferFpsResponse.dstAccountName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(srcBalanceAfter, dstAccountName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoneyTransferFpsResponse {\n");
    
    sb.append("    srcBalanceAfter: ").append(toIndentedString(srcBalanceAfter)).append("\n");
    sb.append("    dstAccountName: ").append(toIndentedString(dstAccountName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

