/*
 * BOCHK FinTech Hackathon 2018 API (Frontend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.oauth.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StockPrice
 */
public class StockPrice {
  @SerializedName("stock_code")
  private String stockCode = null;

  @SerializedName("name_en")
  private String nameEn = null;

  @SerializedName("name_tc")
  private String nameTc = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("change")
  private Double change = null;

  @SerializedName("change_pct")
  private Double changePct = null;

  @SerializedName("pe_ratio")
  private Double peRatio = null;

  @SerializedName("turnover")
  private Long turnover = null;

  public StockPrice stockCode(String stockCode) {
    this.stockCode = stockCode;
    return this;
  }

   /**
   * Get stockCode
   * @return stockCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStockCode() {
    return stockCode;
  }

  public void setStockCode(String stockCode) {
    this.stockCode = stockCode;
  }

  public StockPrice nameEn(String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

   /**
   * Get nameEn
   * @return nameEn
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNameEn() {
    return nameEn;
  }

  public void setNameEn(String nameEn) {
    this.nameEn = nameEn;
  }

  public StockPrice nameTc(String nameTc) {
    this.nameTc = nameTc;
    return this;
  }

   /**
   * Get nameTc
   * @return nameTc
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNameTc() {
    return nameTc;
  }

  public void setNameTc(String nameTc) {
    this.nameTc = nameTc;
  }

  public StockPrice price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public StockPrice change(Double change) {
    this.change = change;
    return this;
  }

   /**
   * Absolute change
   * @return change
  **/
  @ApiModelProperty(required = true, value = "Absolute change")
  public Double getChange() {
    return change;
  }

  public void setChange(Double change) {
    this.change = change;
  }

  public StockPrice changePct(Double changePct) {
    this.changePct = changePct;
    return this;
  }

   /**
   * Percentage change
   * @return changePct
  **/
  @ApiModelProperty(required = true, value = "Percentage change")
  public Double getChangePct() {
    return changePct;
  }

  public void setChangePct(Double changePct) {
    this.changePct = changePct;
  }

  public StockPrice peRatio(Double peRatio) {
    this.peRatio = peRatio;
    return this;
  }

   /**
   * Get peRatio
   * @return peRatio
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPeRatio() {
    return peRatio;
  }

  public void setPeRatio(Double peRatio) {
    this.peRatio = peRatio;
  }

  public StockPrice turnover(Long turnover) {
    this.turnover = turnover;
    return this;
  }

   /**
   * Get turnover
   * @return turnover
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getTurnover() {
    return turnover;
  }

  public void setTurnover(Long turnover) {
    this.turnover = turnover;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockPrice stockPrice = (StockPrice) o;
    return Objects.equals(this.stockCode, stockPrice.stockCode) &&
        Objects.equals(this.nameEn, stockPrice.nameEn) &&
        Objects.equals(this.nameTc, stockPrice.nameTc) &&
        Objects.equals(this.price, stockPrice.price) &&
        Objects.equals(this.change, stockPrice.change) &&
        Objects.equals(this.changePct, stockPrice.changePct) &&
        Objects.equals(this.peRatio, stockPrice.peRatio) &&
        Objects.equals(this.turnover, stockPrice.turnover);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stockCode, nameEn, nameTc, price, change, changePct, peRatio, turnover);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockPrice {\n");
    
    sb.append("    stockCode: ").append(toIndentedString(stockCode)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    nameTc: ").append(toIndentedString(nameTc)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    changePct: ").append(toIndentedString(changePct)).append("\n");
    sb.append("    peRatio: ").append(toIndentedString(peRatio)).append("\n");
    sb.append("    turnover: ").append(toIndentedString(turnover)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

