/*
 * BOCHK FinTech Hackathon 2018 API (Backend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.functional.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Body1
 */
public class Body1 {
  /**
   * Gets or Sets areYouSure
   */
  @JsonAdapter(AreYouSureEnum.Adapter.class)
  public enum AreYouSureEnum {
    YES("YES"),
    
    NO("NO");

    private String value;

    AreYouSureEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AreYouSureEnum fromValue(String text) {
      for (AreYouSureEnum b : AreYouSureEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AreYouSureEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AreYouSureEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AreYouSureEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AreYouSureEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("are_you_sure")
  private AreYouSureEnum areYouSure = null;

  public Body1 areYouSure(AreYouSureEnum areYouSure) {
    this.areYouSure = areYouSure;
    return this;
  }

   /**
   * Get areYouSure
   * @return areYouSure
  **/
  @ApiModelProperty(required = true, value = "")
  public AreYouSureEnum getAreYouSure() {
    return areYouSure;
  }

  public void setAreYouSure(AreYouSureEnum areYouSure) {
    this.areYouSure = areYouSure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return Objects.equals(this.areYouSure, body1.areYouSure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(areYouSure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("    areYouSure: ").append(toIndentedString(areYouSure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

