/*
 * BOCHK FinTech Hackathon 2018 API (Backend)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.14 (20180124)
 * Contact: it_innovation_lab@bochk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bochk.hackathon.api.functional.model;

import java.util.Objects;
import com.bochk.hackathon.api.functional.model.Currency;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PersonalLoanCheckRateResponse
 */
public class PersonalLoanCheckRateResponse {
  @SerializedName("currency")
  private Currency currency = null;

  @SerializedName("amount")
  private Long amount = null;

  @SerializedName("no_of_terms")
  private Long noOfTerms = null;

  @SerializedName("rate")
  private Double rate = null;

  @SerializedName("installment_amount")
  private Long installmentAmount = null;

  @SerializedName("remark")
  private String remark = null;

  public PersonalLoanCheckRateResponse currency(Currency currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "")
  public Currency getCurrency() {
    return currency;
  }

  public void setCurrency(Currency currency) {
    this.currency = currency;
  }

  public PersonalLoanCheckRateResponse amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Amount to loan (in dollar)
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "Amount to loan (in dollar)")
  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public PersonalLoanCheckRateResponse noOfTerms(Long noOfTerms) {
    this.noOfTerms = noOfTerms;
    return this;
  }

   /**
   * Number of installments (monthly)
   * @return noOfTerms
  **/
  @ApiModelProperty(required = true, value = "Number of installments (monthly)")
  public Long getNoOfTerms() {
    return noOfTerms;
  }

  public void setNoOfTerms(Long noOfTerms) {
    this.noOfTerms = noOfTerms;
  }

  public PersonalLoanCheckRateResponse rate(Double rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Annual interest rate (%)
   * @return rate
  **/
  @ApiModelProperty(required = true, value = "Annual interest rate (%)")
  public Double getRate() {
    return rate;
  }

  public void setRate(Double rate) {
    this.rate = rate;
  }

  public PersonalLoanCheckRateResponse installmentAmount(Long installmentAmount) {
    this.installmentAmount = installmentAmount;
    return this;
  }

   /**
   * Amount to repay in each installment
   * @return installmentAmount
  **/
  @ApiModelProperty(required = true, value = "Amount to repay in each installment")
  public Long getInstallmentAmount() {
    return installmentAmount;
  }

  public void setInstallmentAmount(Long installmentAmount) {
    this.installmentAmount = installmentAmount;
  }

  public PersonalLoanCheckRateResponse remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * Free text remark
   * @return remark
  **/
  @ApiModelProperty(value = "Free text remark")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonalLoanCheckRateResponse personalLoanCheckRateResponse = (PersonalLoanCheckRateResponse) o;
    return Objects.equals(this.currency, personalLoanCheckRateResponse.currency) &&
        Objects.equals(this.amount, personalLoanCheckRateResponse.amount) &&
        Objects.equals(this.noOfTerms, personalLoanCheckRateResponse.noOfTerms) &&
        Objects.equals(this.rate, personalLoanCheckRateResponse.rate) &&
        Objects.equals(this.installmentAmount, personalLoanCheckRateResponse.installmentAmount) &&
        Objects.equals(this.remark, personalLoanCheckRateResponse.remark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, amount, noOfTerms, rate, installmentAmount, remark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonalLoanCheckRateResponse {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    noOfTerms: ").append(toIndentedString(noOfTerms)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    installmentAmount: ").append(toIndentedString(installmentAmount)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

