package com.bochk.hackathon.api.test

const val ERROR_AUTH_CODE_GRANT_REQUIRED = "authCodeGrantRequired"
const val ERROR_CLIENT_CRED_GRANT_REQUIRED = "clientCredGrantRequired"

const val ERROR_BRANCH_CODE_REQUIRED = "branchCodeRequired"
const val ERROR_DATETIME_REQUIRED = "datetimeRequired"
const val ERROR_REQUESTED_SERVICE_CATEGORY_REQUIRED = "requestedServiceCategoryRequired"
const val ERROR_ACTION_REQUIRED = "actionRequired"
const val ERROR_UNIT_PRICE_REQUIRED = "unitPriceRequired"
const val ERROR_QUANTITY_REQUIRED = "quantityRequired"
const val ERROR_AMOUNT_REQUIRED = "amountRequired"
const val ERROR_CURRENCY_REQUIRED = "currencyRequired"
const val ERROR_INPUT_REQUIRED = "inputRequired"
const val ERROR_SRC_CURRENCY_REQUIRED = "srcCurrencyRequired"
const val ERROR_DST_CURRENCY_REQUIRED = "dstCurrencyRequired"
const val ERROR_DST_ACCOUNT_NO_REQUIRED = "dstAccountNoRequired"
const val ERROR_RATE_REQUIRED = "rateRequired"
const val ERROR_DST_INFO_TYPE_REQUIRED = "dstInfoTypeRequired"
const val ERROR_DST_INFO_REQUIRED = "dstInfoRequired"
const val ERROR_CONFIRMATION_REQUIRED = "confirmationRequired"

const val ERROR_INVALID_PHONE_NO = "invalidPhoneNo"
const val ERROR_INVALID_DATETIME = "invalidDatetime"
const val ERROR_INVALID_DATE = "invalidDate"
const val ERROR_INVALID_REQUESTED_SERVICE_CATEGORY = "invalidRequestedServiceCategory"
const val ERROR_INVALID_BRANCH_CODE = "invalidBranchCode"
const val ERROR_INVALID_LOAN_RATE = "invalidLoanRate"
const val ERROR_INVALID_INSTALLMENT_AMOUNT = "invalidInstallmentAmount"
const val ERROR_INVALID_CURRENCY = "invalidCurrency"
const val ERROR_INVALID_CUSTOMER_ID = "invalidCustomerId"
const val ERROR_INVALID_STOCK_CODE = "invalidStockCode"
const val ERROR_INVALID_ACCOUNT_NO = "invalidAccountNo"
const val ERROR_INVALID_STOCK_UNIT_PRICE = "invalidStockUnitPrice"
const val ERROR_INVALID_AMOUNT = "invalidAmount"
const val ERROR_INVALID_RATE = "invalidRate"
const val ERROR_INVALID_DST_INFO_TYPE = "invalidDstInfoType"
const val ERROR_INVALID_NO_OF_TERMS = "invalidNoOfTerms"

const val ERROR_APPOINTMENT_NOT_FOUND = "appointmentNotFound"
const val ERROR_CREDIT_CARD_NOT_FOUND = "creditCardNotFound"
const val ERROR_ACCOUNT_NOT_FOUND = "accountNotFound"
const val ERROR_DST_ACCOUNT_NOT_FOUND = "dstAccountNotFound"
const val ERROR_STOCK_NOT_FOUND = "stockNotFound"
const val ERROR_CURRENCY_NOT_FOUND = "currencyNotFound"

const val ERROR_INSUFFICIENT_CREDIT = "insufficientCredit"
const val ERROR_INSUFFICIENT_ACCOUNT_BALANCE = "insufficientAccountBalance"
const val ERROR_INSUFFICIENT_STOCK = "insufficientStock"

const val ERROR_ACCOUNT_MUST_BE_DIFFERENT = "accountMustBeDifferent"
const val ERROR_CUSTOMER_MUST_BE_THE_SAME = "customerMustBeTheSame"
const val ERROR_CUSTOMER_MUST_BE_DIFFERENT = "customerMustBeDifferent"
const val ERROR_CURRENCY_MUST_BE_DIFFERENT = "currencyMustBeDifferent"

const val ERROR_INTERNAL = "internalError"
const val ERROR_INVALID_INPUT = "invalidInput"
